### ISSUE TITLE
Multithreading overwrites global variables

### ISSUE THREAD

**Issue by MartinMReed** [jjguy/heatmap#18]
Thanks for providing this library.

I am running this from web.py for creating map tiles. In order to get a full dot to span multiple tiles I have to include that point on each tile that displays any part of the dot. So some dots are drawn outside of the 'area'. Thats all fine and working, however I noticed that sometimes a part of a dot is duplicated on two tiles. Its not reproducible every time, so that makes me believe it is a timing/threading issue. I believe this is caused by having the 'area' variables as global instead of encapsulated in a struct so they are local to the method and not the whole shared lib.

After moving all of the global variables to a struct I am no longer seeing this issue.

Below is an example of what I mean by duplicated. The dots in the green squares are expected. The others are duplicates.

![img_2973](https://cloud.githubusercontent.com/assets/476221/2822399/3d0f551a-cf12-11e3-82e9-14ce57020b89.PNG)

**Comment by jjguy** [comment]
fixed in #19
