### ISSUE TITLE
pip and easy_install fail

### ISSUE THREAD

**Issue by gh-ahardin** [jjguy/heatmap#7]
Hi!  I get a setup error when installing with either easy_install or pip:
$pip install heatmap
Downloading/unpacking heatmap
  Downloading heatmap-2.2.tar.gz
  Running setup.py egg_info for package heatmap
    error in heatmap setup command: test_suite must be a string
    Complete output from command python setup.py egg_info:
    error in heatmap setup command: test_suite must be a string

---

Command python setup.py egg_info failed with error code 1 in /var/folders/1j/lkx2dg7d7tn6f4t4c6lwmt9r0000gq/T/pip-build/heatmap

**Comment by ghost** [comment]
# I'm getting the same error using easy_install:

$ easy_install heatmap
Searching for heatmap
Reading http://pypi.python.org/simple/heatmap/
Reading http://jjguy.com/heatmap/
Best match: heatmap 2.2
Downloading http://jjguy.com/heatmap/heatmap-2.2.zip
Processing heatmap-2.2.zip
Running heatmap-2.2/setup.py -q bdist_egg --dist-dir /var/folders/82/82-OubL8H-09LeOxGtKPLE+++TM/-Tmp-/easy_install-5nzMFu/heatmap-2.2/egg-dist-tmp-X8NAin
error: Setup script exited with error in heatmap setup command: test_suite must be a string

(This is on a Mac, running Snow Leopard 10.6.8)

**Comment by jjguy** [comment]
llonchj found/fixed this particular bug with the following commit:

https://github.com/jjguy/heatmap/commit/29c0e056db5b9fd9ebcb1a6c47e2e8470c257240

That's pushed as 2.2.1.  pip install appears to work:

`[root@localhost pip-1.2.1]# easy_install heatmap
Searching for heatmap
Reading http://pypi.python.org/simple/heatmap/
Reading http://jjguy.com/heatmap/
Best match: heatmap 2.2.1
Downloading http://jjguy.com/heatmap/heatmap-2.2.1.zip
Processing heatmap-2.2.1.zip
Running heatmap-2.2.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-NqLtUD/heatmap-2.2.1/egg-dist-tmp-RMyYR1
zip_safe flag not set; analyzing archive contents...
Adding heatmap 2.2.1 to easy-install.pth file
Installed /usr/lib/python2.6/site-packages/heatmap-2.2.1-py2.6-linux-x86_64.egg
Processing dependencies for heatmap
Finished processing dependencies for heatmap`
