### ISSUE TITLE
hm = heatmap.Heatmap()

### ISSUE THREAD

**Issue by artyak** [jjguy/heatmap#8]
Hi there,

I'm new to python but I saw your module for GoogleEarth and really really want to use it. I've managed to install the module but am struggling to complete the examples. I just have a few quick questions and I would really appreciate any kind of help or advice for how to get the .kml output to display. 
These first two parts work fine:
###### 

import heatmap
import random
###### 

then i get to 
###### 

hm = heatmap.Heatmap() 
###### 

and I get the error message "WindowsError: [Error 126] The specified module could not be found"

From looking around online apparently there could be an issue with the location of the .dll? I also saw there was a previous issue dealing with "from heatmap import Heatmap"...is that related?

Honestly I'm not even sure if I should be working in the windows command line or in IDLE. 

I really think this module can do exactly what I need (creating a crime density overlay) so I'm not ready to give up. Help please!

**Comment by jjguy** [comment]
Closing as duplicate.
